version 2.1


workflows:
  configure:
    jobs:
      - configure_infrastructure

jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["66:b7:e9:a8:86:0d:3a:23:23:cf:7d:40:56:fb:65:60"] 
      - run:
          name: Install dependencies
          command: |
            # install the dependencies needed for playbook
            apk add --update ansible 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

